### PR TITLE
GENDER

### PR DESCRIPTION
**Pull request by falcotinnunculus**
Add gender support to bot

### CODE REVIEW

**Comment by dtracz** [comment]
1. Please remove commented print from line 74.
2. Use "My Lady" instead of "Ma'am". Seriously it seems more respectful.
3. Using 'Sir' as a variable name that could by set to "Sir" of "My Lady" is a bit confusing. "title" maybe? But more important is that a variable shouldn't start with capital letter.
4. I used old python sting formatting because I find new way less elegant, not because I don't know it. But looks like I'm in minority, so let it be as it is now.

**Comment by dtracz** [comment]
5. Are "TEST" or "NICK" are in use right now? Or are they just feature stubs, that will be add in the future? If so, please remove it for now, and add whole feature as one PR. Lets not merge to master partial functionalities.

**Comment by bartosz-zbik** [comment]
My three commits should solve all problems listed by dtracz.

**Comment by dtracz** [comment]
Now looks awesome! You can merge

**Pull request merged**
